# Generated by Django 4.2.5 on 2024-03-15 18:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id_release', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nm_release', models.CharField(max_length=100)),
                ('ds_release', models.CharField(max_length=500)),
                ('ph_release', models.ImageField(upload_to='ph_release/')),
                ('fg_release', models.CharField(max_length=10)),
            ],
        ),
    ]
