# Generated by Django 4.2.5 on 2024-03-15 18:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id_artist', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nm_artist', models.CharField(max_length=100)),
                ('ds_artist', models.CharField(max_length=500)),
                ('ph_artist', models.ImageField(upload_to='ph_artist/')),
            ],
        ),
    ]
