# Generated by Django 4.2.5 on 2023-09-08 11:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id_release', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nm_release', models.CharField(max_length=100)),
                ('ds_release', models.CharField(max_length=500)),
                ('ph_release', models.BinaryField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id_song', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nm_song', models.CharField(max_length=100)),
                ('ds_song', models.CharField(max_length=500)),
                ('sg_song', models.BinaryField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.release')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id_track', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nm_track', models.CharField(max_length=100)),
                ('ds_track', models.CharField(max_length=500)),
                ('sg_track', models.BinaryField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.song')),
            ],
        ),
    ]
