# Generated by Django 4.2.5 on 2023-09-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_remove_release_artist_delete_track_delete_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='ph_artist',
            field=models.CharField(max_length=500),
        ),
    ]
